theory proofs
  imports mechanized
begin

text \<open>
  Top-level termination of the Pair Sequence System.
  (File named \<open>proofs.thy\<close> rather than \<open>proof.thy\<close>: \<open>proof\<close> is an Isabelle
  keyword and cannot be a theory name.)

  Termination — no infinite expansion chain on the standard form
  \<open>ST_PS\<close> — is reduced to two facts about the \<open>p_a(b)+c\<close> measure \<open>translate\<close>:
    \<^item> \<open>dec\<close>: each expansion step strictly decreases \<open>translate\<close> — \<^bold>\<open>DONE\<close>,
      @{thm [source] m_step_decreases};
    \<^item> \<open>wfimg\<close>: the subscript-first order \<open><o\<close> is well-founded on the image
      \<open>NF = translate ` ST_PS\<close> — the Buchholz-level core, still open.

  @{text step_terminates} discharges \<open>dec\<close> from @{thm [source] m_step_decreases},
  so termination now hinges on \<open>wfimg\<close> alone.
\<close>

abbreviation NF :: "ord set" where
  "NF \<equiv> translate ` ST_PS"

abbreviation Rnf :: "(ord \<times> ord) set" where
  "Rnf \<equiv> {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF}"

text \<open>
  \<^bold>\<open>Reduction of \<open>wfimg\<close> to diagonal accessibility.\<close>

  Accessibility under \<open>Rnf\<close> is downward closed (@{thm [source] acc_downward}).
  The standard form \<open>ST_PS\<close> is generated by two rules: diagonals \<open>diagSeq u v\<close>,
  and the expansion \<open>M \<mapsto> M[n]\<close>.  For the expansion rule the decrease lemma
  @{thm [source] m_step_decreases} gives \<open>translate (M[n]) <o translate M\<close>, i.e.
  \<open>(translate (M[n]), translate M) \<in> Rnf\<close>; so if \<open>translate M\<close> is accessible,
  then \<open>translate (M[n])\<close> is accessible \<^emph>\<open>for free\<close>.  Consequently the \<^emph>\<open>entire\<close>
  well-foundedness obligation \<open>wfimg\<close> collapses to a single residual fact: every
  diagonal tower \<open>translate (diagSeq u v) = p\<^bsub>u\<^esub>(p\<^bsub>u+1\<^esub>(\<dots>p\<^bsub>v\<^esub>(0)))\<close> is
  \<open>Rnf\<close>-accessible.  This isolates the genuine Buchholz-level (\<open>\<psi>\<close>-collapsing)
  content to the diagonals, discharging the whole expansion side via the
  already-proven decrease lemma.
\<close>

lemma oper_eq_self_short:
  assumes "Lng M \<le> 1"
  shows "M[n] = M"
proof -
  from assms have "Lng M - 1 = 0" by simp
  thus ?thesis by (simp add: oper_def)
qed

lemma acc_Rnf_of_ST_PS:
  assumes diagacc: "\<And>u v. u \<le> v \<Longrightarrow> translate (diagSeq u v) \<in> Wellfounded.acc Rnf"
    and "M \<in> ST_PS"
  shows "translate M \<in> Wellfounded.acc Rnf"
  using \<open>M \<in> ST_PS\<close>
proof (induction M rule: ST_PS.induct)
  case (diag u v)
  thus ?case using diagacc by simp
next
  case (oper M n)
  show ?case
  proof (cases "1 < Lng M")
    case False
    hence "M[n] = M" by (simp add: oper_eq_self_short)
    thus ?thesis using oper.IH by simp
  next
    case True
    have dec: "translate (M[n]) <o translate M"
      using m_step_decreases[OF True oper.hyps(2)] .
    have mnf: "translate M \<in> NF" using oper.hyps(1) by (rule imageI)
    have mnnf: "translate (M[n]) \<in> NF"
      using ST_PS.oper[OF oper.hyps(1) oper.hyps(2)] by (rule imageI)
    have step_in: "(translate (M[n]), translate M) \<in> Rnf"
      using dec mnf mnnf by simp
    show ?thesis by (rule acc_downward[OF oper.IH step_in])
  qed
qed

theorem wf_Rnf_from_diag:
  assumes diagacc: "\<And>u v. u \<le> v \<Longrightarrow> translate (diagSeq u v) \<in> Wellfounded.acc Rnf"
  shows "wf Rnf"
proof -
  have "x \<in> Wellfounded.acc Rnf" for x
  proof (cases "x \<in> NF")
    case True
    then obtain M where "M \<in> ST_PS" "x = translate M" by auto
    thus ?thesis using acc_Rnf_of_ST_PS[OF diagacc] by simp
  next
    case False
    show ?thesis
    proof (rule acc.accI)
      fix y assume "(y, x) \<in> Rnf"
      hence "x \<in> NF" by simp
      with False show "y \<in> Wellfounded.acc Rnf" by simp
    qed
  qed
  thus "wf Rnf" by (simp add: wf_iff_acc)
qed

text \<open>The expansion step lands inside \<open>ST_PS\<close> and inside \<open>NF\<close>.\<close>

lemma step_in_ST_PS:
  assumes "M \<in> ST_PS" and "step M T"
  shows "T \<in> ST_PS"
proof -
  from \<open>step M T\<close> obtain n where n: "1 \<le> n" and TM: "T = M[n]"
    by (auto elim: step.cases)
  show ?thesis using ST_PS.oper[OF \<open>M \<in> ST_PS\<close> n] TM by simp
qed

text \<open>Conditional termination: decrease + well-foundedness on the image give
  well-foundedness of the one-step relation on \<open>ST_PS\<close>.\<close>

theorem step_terminates_cond:
  assumes dec: "\<And>M n. M \<in> ST_PS \<Longrightarrow> 1 < Lng M \<Longrightarrow> 1 \<le> n \<Longrightarrow> translate (M[n]) <o translate M"
    and wfimg: "wf {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF}"
  shows "wf {(T,M). M \<in> ST_PS \<and> step M T}"
proof (rule wf_subset)
  show "wf (inv_image {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF} translate)"
    by (rule wf_inv_image[OF wfimg])
next
  show "{(T,M). M \<in> ST_PS \<and> step M T}
          \<subseteq> inv_image {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF} translate"
  proof (rule subrelI)
    fix T M assume "(T,M) \<in> {(T,M). M \<in> ST_PS \<and> step M T}"
    then have M: "M \<in> ST_PS" and st: "step M T" by auto
    from st obtain n where L: "1 < Lng M" and n: "1 \<le> n" and TM: "T = M[n]"
      by (auto elim!: step.cases)
    have T: "T \<in> ST_PS" using M st by (rule step_in_ST_PS)
    have "translate T <o translate M" using dec[OF M L n] TM by simp
    moreover have "translate M \<in> NF" using M by simp
    moreover have "translate T \<in> NF" using T by simp
    ultimately show "(T,M) \<in> inv_image {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF} translate"
      by (simp add: inv_image_def)
  qed
qed

text \<open>Equivalent phrasing: there is no infinite expansion sequence within
  \<open>ST_PS\<close>.\<close>

corollary no_infinite_expansion_cond:
  assumes dec: "\<And>M n. M \<in> ST_PS \<Longrightarrow> 1 < Lng M \<Longrightarrow> 1 \<le> n \<Longrightarrow> translate (M[n]) <o translate M"
    and wfimg: "wf {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF}"
  shows "\<not> (\<exists>S. (\<forall>i. S i \<in> ST_PS) \<and> (\<forall>i. step (S i) (S (Suc i))))"
proof
  assume "\<exists>S. (\<forall>i. S i \<in> ST_PS) \<and> (\<forall>i. step (S i) (S (Suc i)))"
  then obtain S where S: "\<And>i. S i \<in> ST_PS" and stp: "\<And>i. step (S i) (S (Suc i))" by auto
  let ?R = "{(T,M). M \<in> ST_PS \<and> step M T}"
  have wf: "wf ?R" by (rule step_terminates_cond[OF dec wfimg])
  have chain: "\<forall>i. (S (Suc i), S i) \<in> ?R" using S stp by auto
  from wf have "\<not> (\<exists>f. \<forall>i. (f (Suc i), f i) \<in> ?R)"
    by (simp add: wf_iff_no_infinite_down_chain)
  with chain show False by blast
qed


text \<open>Discharging \<open>dec\<close> by the proved decrease lemma, termination of the pair
  sequence system reduces to well-foundedness of \<open><o\<close> on \<open>NF\<close> alone.\<close>

theorem step_terminates:
  assumes wfimg: "wf {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF}"
  shows "wf {(T,M). M \<in> ST_PS \<and> step M T}"
proof (rule step_terminates_cond[OF _ wfimg])
  fix M and n :: nat assume "M \<in> ST_PS" "1 < Lng M" "1 \<le> n"
  thus "translate (M[n]) <o translate M" using m_step_decreases by blast
qed

corollary no_infinite_expansion:
  assumes wfimg: "wf {(v,u). v <o u \<and> u \<in> NF \<and> v \<in> NF}"
  shows "\<not> (\<exists>S. (\<forall>i. S i \<in> ST_PS) \<and> (\<forall>i. step (S i) (S (Suc i))))"
proof (rule no_infinite_expansion_cond[OF _ wfimg])
  fix M and n :: nat assume "M \<in> ST_PS" "1 < Lng M" "1 \<le> n"
  thus "translate (M[n]) <o translate M" using m_step_decreases by blast
qed


text \<open>Termination phrased against the residual diagonal-accessibility obligation:
  feeding @{thm [source] wf_Rnf_from_diag} into the termination theorems above
  turns \<open>wfimg\<close> into the single hypothesis \<open>diagacc\<close>.\<close>

theorem step_terminates_from_diag:
  assumes diagacc: "\<And>u v. u \<le> v \<Longrightarrow> translate (diagSeq u v) \<in> Wellfounded.acc Rnf"
  shows "wf {(T,M). M \<in> ST_PS \<and> step M T}"
  by (rule step_terminates[OF wf_Rnf_from_diag[OF diagacc]])

corollary no_infinite_expansion_from_diag:
  assumes diagacc: "\<And>u v. u \<le> v \<Longrightarrow> translate (diagSeq u v) \<in> Wellfounded.acc Rnf"
  shows "\<not> (\<exists>S. (\<forall>i. S i \<in> ST_PS) \<and> (\<forall>i. step (S i) (S (Suc i))))"
  by (rule no_infinite_expansion[OF wf_Rnf_from_diag[OF diagacc]])

end
