/-
Top-level termination of the Pair Sequence System.  Lean port of
`proofs.thy`.

Termination — no infinite expansion chain on the standard form `ST_PS` — is
reduced to two facts about the `p_a(b)+c` measure `translate`:

* `dec`: each expansion step strictly decreases `translate` — **DONE**,
  `m_step_decreases`;
* `wfimg`: the subscript-first order `<o` is well-founded on the image
  `NF = translate '' ST_PS` — the Buchholz-level core, still open (the
  Isabelle side is closing it via `ord/psi.thy` + `nrm.thy`).

`step_terminates` discharges `dec` from `m_step_decreases`, so termination
now hinges on `wfimg` alone.

Port conventions (Isabelle → Lean):
  * `wf R` (set of pairs)  → `WellFounded R` (`R : α → α → Prop`, arguments in
    the same order: `R y x` means "`y` below `x`", i.e. `(y, x) ∈ R`)
  * `Wellfounded.acc R x`  → `Acc R x`
  * `acc_downward`         → `Acc.inv`
  * `wf_inv_image`         → `InvImage.wf`
  * `wf_subset`            → `Subrelation.wf`
-/
import YAPSS.Mechanized

namespace YAPSS

open Three

/-- `NF`: the image of the standard forms under `translate`. -/
def NF : Set Three := {t | ∃ M, ST_PS M ∧ translate M = t}

/-- `Rnf`: the order `<o` restricted to `NF` (as a relation; `Rnf v u` is
Isabelle's `(v, u) ∈ Rnf`). -/
def Rnf (v u : Three) : Prop := v <o u ∧ u ∈ NF ∧ v ∈ NF

theorem oper_eq_self_short {M : PairSeq} (n : ℕ) (h : M.length ≤ 1) :
    M⟦n⟧ = M :=
  oper_eq_self_of_short n (by omega)

/-!
**Reduction of `wfimg` to diagonal accessibility.**

Accessibility under `Rnf` is downward closed (`Acc.inv`).  The standard form
`ST_PS` is generated by two rules: diagonals `diagSeq 0 v`, and the expansion
`M ↦ M⟦n⟧`.  For the expansion rule the decrease lemma `m_step_decreases`
gives `translate (M⟦n⟧) <o translate M`, i.e. `Rnf (translate (M⟦n⟧))
(translate M)`; so if `translate M` is accessible, then `translate (M⟦n⟧)` is
accessible *for free*.  Consequently the *entire* well-foundedness obligation
`wfimg` collapses to a single residual fact: every diagonal tower
`translate (diagSeq 0 v) = p_0(p_1(…p_v(0)))` is `Rnf`-accessible.  This
isolates the genuine Buchholz-level (ψ-collapsing) content to the diagonals,
discharging the whole expansion side via the already-proven decrease lemma.
-/

theorem acc_Rnf_of_ST_PS
    (diagacc : ∀ v, Acc Rnf (translate (diagSeq 0 v)))
    {M : PairSeq} (hM : ST_PS M) :
    Acc Rnf (translate M) := by
  induction hM with
  | diag v => exact diagacc v
  | @oper M n hM hn ih =>
    by_cases L : 1 < M.length
    · have dec : translate (M⟦n⟧) <o translate M := m_step_decreases L hn
      have mnf : translate M ∈ NF := ⟨M, hM, rfl⟩
      have mnnf : translate (M⟦n⟧) ∈ NF := ⟨M⟦n⟧, ST_PS.oper hM hn, rfl⟩
      exact ih.inv ⟨dec, mnf, mnnf⟩
    · rw [oper_eq_self_short n (by omega)]
      exact ih

theorem wf_Rnf_from_diag
    (diagacc : ∀ v, Acc Rnf (translate (diagSeq 0 v))) :
    WellFounded Rnf := by
  refine ⟨fun x => ?_⟩
  by_cases hx : x ∈ NF
  · obtain ⟨M, hM, rfl⟩ := hx
    exact acc_Rnf_of_ST_PS diagacc hM
  · exact Acc.intro x fun y hy => absurd hy.2.1 hx

/-- The expansion step lands inside `ST_PS` (and hence inside `NF`). -/
theorem step_in_ST_PS {M T : PairSeq} (hM : ST_PS M) (hstep : step M T) :
    ST_PS T := by
  cases hstep with
  | step_oper L hn => exact ST_PS.oper hM hn

/-- The one-step relation on standard forms, as a Lean relation
(Isabelle's `{(T, M). M ∈ ST_PS ∧ step M T}`). -/
def stepRel (T M : PairSeq) : Prop := ST_PS M ∧ step M T

/-- Conditional termination: decrease + well-foundedness on the image give
well-foundedness of the one-step relation on `ST_PS`. -/
theorem step_terminates_cond
    (dec : ∀ M n, ST_PS M → 1 < M.length → 1 ≤ n →
      translate (M⟦n⟧) <o translate M)
    (wfimg : WellFounded Rnf) :
    WellFounded stepRel := by
  have hsub : ∀ {T M}, stepRel T M → InvImage Rnf translate T M := by
    intro T M h
    obtain ⟨hM, hstep⟩ := h
    cases hstep with
    | @step_oper n L hn =>
      have hT : ST_PS (M⟦n⟧) := ST_PS.oper hM hn
      exact ⟨dec M n hM L hn, ⟨M, hM, rfl⟩, ⟨M⟦n⟧, hT, rfl⟩⟩
  exact Subrelation.wf hsub (InvImage.wf translate wfimg)

/-- Equivalent phrasing: there is no infinite expansion sequence within
`ST_PS`. -/
theorem no_infinite_expansion_cond
    (dec : ∀ M n, ST_PS M → 1 < M.length → 1 ≤ n →
      translate (M⟦n⟧) <o translate M)
    (wfimg : WellFounded Rnf) :
    ¬ ∃ S : ℕ → PairSeq, (∀ i, ST_PS (S i)) ∧ ∀ i, step (S i) (S (i + 1)) := by
  rintro ⟨S, hS, hstep⟩
  have wf : WellFounded stepRel := step_terminates_cond dec wfimg
  have chain : ∀ i, stepRel (S (i + 1)) (S i) := fun i => ⟨hS i, hstep i⟩
  -- no infinite descending chain in a well-founded relation
  have key : ∀ x, Acc stepRel x → ∀ i, S i = x → False := by
    intro x hacc
    induction hacc with
    | intro x _ ih =>
      intro i hi
      exact ih (S (i + 1)) (hi ▸ chain i) (i + 1) rfl
  exact key (S 0) (wf.apply (S 0)) 0 rfl

/-!
Discharging `dec` by the proved decrease lemma, termination of the pair
sequence system reduces to well-foundedness of `<o` on `NF` alone.
-/

theorem step_terminates (wfimg : WellFounded Rnf) : WellFounded stepRel :=
  step_terminates_cond (fun _ _ _ L hn => m_step_decreases L hn) wfimg

theorem no_infinite_expansion (wfimg : WellFounded Rnf) :
    ¬ ∃ S : ℕ → PairSeq, (∀ i, ST_PS (S i)) ∧ ∀ i, step (S i) (S (i + 1)) :=
  no_infinite_expansion_cond (fun _ _ _ L hn => m_step_decreases L hn) wfimg

/-!
Termination phrased against the residual diagonal-accessibility obligation:
feeding `wf_Rnf_from_diag` into the termination theorems above turns `wfimg`
into the single hypothesis `diagacc`.
-/

theorem step_terminates_from_diag
    (diagacc : ∀ v, Acc Rnf (translate (diagSeq 0 v))) :
    WellFounded stepRel :=
  step_terminates (wf_Rnf_from_diag diagacc)

theorem no_infinite_expansion_from_diag
    (diagacc : ∀ v, Acc Rnf (translate (diagSeq 0 v))) :
    ¬ ∃ S : ℕ → PairSeq, (∀ i, ST_PS (S i)) ∧ ∀ i, step (S i) (S (i + 1)) :=
  no_infinite_expansion (wf_Rnf_from_diag diagacc)

end YAPSS
